In [1]:
import numpy as np

def get_out(a, b):
    return np.concatenate((a, b))

def get_out2(a, b):
    return np.array(list(zip(a, b)))

def get_out3(a, b):
    return np.array([a, b])





a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(get_out(a, b))  # 输出：[1 2 3 4 5 6]
print(get_out2(a, b))  # 输出：[[1 4] [2 5] [3 6]]
print(get_out3(a, b))  # 输出：[[1 2 3] [4 5 6]]

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
